version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pdf_pipeline_postgres
    environment:
      - POSTGRES_USER=pdfuser
      - POSTGRES_PASSWORD=securepass123
      - POSTGRES_DB=pdf_pipeline
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - pdf_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pdf_pipeline_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pdfpipeline.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pdf_network

networks:
  pdf_network:
    driver: bridge